name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  format:
    name: Code linting
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Elixir environment
        uses: erlef/setup-beam@v1
        with:
          otp-version: "26"
          elixir-version: "1.15"

      - name: Check unused dependencies
        run: mix deps.get && mix deps.unlock --check-unused

      - name: Check formatting
        run: mix format --check-formatted

  test:
    name: Test suite
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        versions:
          - otp: "20"
            elixir: "1.6"
          - otp: "26"
            elixir: "1.15"

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v3

      - name: Set up Elixir environment
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.versions.elixir }}
          otp-version: ${{ matrix.versions.otp }}

      - name: Install dependencies
        run: mix deps.get --only test

      - name: Run tests
        run: mix test
