name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Code linting
    uses: lexmag/elixir-actions/.github/workflows/lint.yml@v2
    with:
      otp-version: "25"
      elixir-version: "1.15"

  test:
    name: Test suite
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        versions:
          - otp: "20"
            elixir: "1.9"
          - otp: "26"
            elixir: "1.15"

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v3

      - name: Set up Elixir environment
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.versions.elixir }}
          otp-version: ${{ matrix.versions.otp }}

      - name: Install dependencies
        run: mix deps.get --only test

      - name: Run tests
        run: mix test
